server:
  port: 7001  # Spring Boot 애플리케이션이 실행될 포트

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: data-visualization-service  # Eureka에 등록할 서비스 이름
  data:
    elasticsearch:
      rest:
        uris: http://localhost:9200   # Elasticsearch REST API URL
        headers:
          Authorization:  "Basic ZWxhc3RpYzpmVlR0dipRQj1hOEpaQW91SzBJcg==" # "elastic:fVTtv*QB=a8JZAouK0Ir" 가 인코딩된 문자열 사용

